# Builds src/index.html (runs locally, no server needed) from:
#   src/artifact-page.html  - the exact source published to claude.ai
#   src/shim.js             - localStorage-backed window.claude.use("db" | "downloads")
#   data/example-orders.json - embedded so ?seed=1 works when opened straight from disk
# Edit artifact-page.html, then re-run this script. Never edit index.html by hand.
$root = Split-Path $PSScriptRoot -Parent
$utf8 = New-Object Text.UTF8Encoding $false
$page = [IO.File]::ReadAllText((Join-Path $root 'src\artifact-page.html'), $utf8)
$shim = [IO.File]::ReadAllText((Join-Path $root 'src\shim.js'), $utf8)
$data = [IO.File]::ReadAllText((Join-Path $root 'data\example-orders.json'), $utf8) -replace '</', '<\/'
$out = @"
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<!-- GENERATED by tools/build.ps1 - edit src/artifact-page.html instead -->
<style>body{margin:0;padding:0;font:14px -apple-system,BlinkMacSystemFont,sans-serif}[hidden]{display:none!important}</style>
<script type="application/json" id="example-orders">$data</script>
<script>
$shim
</script>
</head><body>
$page
</body></html>
"@
[IO.File]::WriteAllText((Join-Path $root 'src\index.html'), $out, $utf8)
"Built src/index.html ($((Get-Item (Join-Path $root 'src\index.html')).Length) bytes)"

# docs/ is the online version served by GitHub Pages: same page, Firebase instead of localStorage.
$fbShim = [IO.File]::ReadAllText((Join-Path $root 'src\firebase-shim.js'), $utf8)
$fbVer = '10.14.1'
$web = @"
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<!-- GENERATED by tools/build.ps1 - edit src/artifact-page.html instead -->
<style>body{margin:0;padding:0;font:14px -apple-system,BlinkMacSystemFont,sans-serif}[hidden]{display:none!important}</style>
<script src="https://www.gstatic.com/firebasejs/$fbVer/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/$fbVer/firebase-auth-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/$fbVer/firebase-firestore-compat.js"></script>
<script src="firebase-config.js"></script>
<script>
$fbShim
</script>
</head><body>
$page
</body></html>
"@
$docs = Join-Path $root 'docs'
New-Item -ItemType Directory -Force $docs | Out-Null
[IO.File]::WriteAllText((Join-Path $docs 'index.html'), $web, $utf8)
$cfg = Join-Path $docs 'firebase-config.js'
if (-not (Test-Path $cfg)) { Copy-Item (Join-Path $root 'src\firebase-config.js') $cfg }
[IO.File]::WriteAllText((Join-Path $docs '.nojekyll'), '', $utf8)
"Built docs/index.html for GitHub Pages"
